name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: cd scpi
      run: cd scpi
    - name: make
      run: make
